workflows:
  expo-build:
    name: Build Expo app
    max_build_duration: 60
    environment:
      vars:
        EXPO_APPLE_ACCOUNT_EMAIL: $EXPO_APPLE_ACCOUNT_EMAIL
        EXPO_ANDROID_KEYSTORE_BASE64: $EXPO_ANDROID_KEYSTORE_BASE64
        EXPO_ANDROID_KEYSTORE_PASSWORD: $EXPO_ANDROID_KEYSTORE_PASSWORD
        EXPO_ANDROID_KEY_PASSWORD: $EXPO_ANDROID_KEY_PASSWORD
        EXPO_ANDROID_KEY_ALIAS: $EXPO_ANDROID_KEY_ALIAS
      node: 18
      yarn: false
    scripts:
      - name: Install Expo CLI
        script: npm install -g expo-cli
      - name: Install dependencies
        script: npm install
      - name: Expo prebuild (optional for managed workflow)
        script: expo install
      - name: Build Android
        script: expo build:android --non-interactive
      - name: Build iOS
        script: expo build:ios --non-interactive
    artifacts:
      - build/**/*
