workflows:
  expo-app:
    name: Build Expo App
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      vars:
        EXPO_APPLE_ACCOUNT_EMAIL: $EXPO_APPLE_ACCOUNT_EMAIL
        EXPO_APPLE_ACCOUNT_PASSWORD: $EXPO_APPLE_ACCOUNT_PASSWORD
      node: 18.16.0
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Install Expo CLI
        script: npm install -g expo-cli
      - name: Build app
        script: |
          expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          expo build:android --non-interactive
    artifacts:
      - build/**/*
