workflows:
  expo-app:
    name: Build Expo App
    instance_type: linux_x2
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.16.0
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Install Expo CLI
        script: npm install -g expo-cli
      - name: Build Expo app
        script: expo export --output-dir=dist
    artifacts:
      - dist/**/*
