workflows:
  expo-build:
    name: Expo Build
    max_build_duration: 45
    environment:
      vars:
        EXPO_TOKEN: Encrypted_Expo_Token_Here
      node: 18
    scripts:
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli
      - name: Install dependencies
        script: |
          npm install
      - name: Expo Prebuild (Optional for Bare workflow)
        script: |
          npx expo prebuild --no-install || true
      - name: Build app
        script: |
          npx expo export --platform android
    artifacts:
      - dist/**

